# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-16 20:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0006_image_categories'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='categories',
            new_name='category',
        ),
    ]
