# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-09 02:43
from __future__ import unicode_literals

from django.db import migrations
import tagulous.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0008_auto_20180113_2312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='tags',
            field=tagulous.models.fields.TagField(_set_tag_meta=True, blank=True, help_text='Enter a comma-separated tag string', space_delimiter=False, to='images.ImageTag'),
        ),
    ]
