# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-28 00:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imageshare', '0002_image_datetime_uploaded'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='datetime_uploaded',
            new_name='uploaded_date',
        ),
    ]
