# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-16 20:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imageshare', '0005_image_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='categories',
            field=models.CharField(choices=[('ABSTRACT', 'abstract'), ('ANIMALS', 'animals'), ('ARCHITECTURE', 'architecture'), ('FANTASY', 'fantasy'), ('FOOD', 'food'), ('HOLIDAYS', 'holidays'), ('MISC', 'misc'), ('MUSIC', 'music'), ('NATURE', 'nature'), ('SCI-FI', 'sci-fi'), ('SPACE', 'space'), ('SPORTS', 'sports'), ('VEHICLES', 'vehicles')], default='MISC', max_length=20),
        ),
    ]
