# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-22 03:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_profile_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(blank=True, choices=[('-', 'unspecified'), ('m', 'male'), ('f', 'female')], max_length=1),
        ),
    ]
