# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-04 00:58
from __future__ import unicode_literals

import apps.accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20170622_0340'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(
                blank=True, null=True, upload_to=apps.accounts.models.get_image_path),
        ),
    ]
