# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-16 20:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20170704_0100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(blank=True, choices=[('-', ''), ('m', 'male'), ('f', 'female')], max_length=1),
        ),
    ]
